### PR TITLE
UI improvements

### PR DESCRIPTION
**Pull request by marySalvi**
- Adds a loading feedback on the filebrowser
- Makes the Image Data Table 'denser', expand across more of the page and increases image preview size (slightly)
- Image lists for the filebrowser are created dynamically based on the space available.

### CODE REVIEW

**Comment by marySalvi** [comment]
@manthey  I believe this should also resolve #250. Would you mind checking when you review? Thanks!

**Comment by manthey** [comment]
The "Collecting Directory Data" message doesn't go away; I was selecting an empty directory for output.

**Comment by manthey** [comment]
I'm getting outer scroll bars on the page:
image

**Comment by marySalvi** [comment]
> I'm getting outer scroll bars on the page:

hopefully fixed in d6b0b72259b3a849123bb19c7a6c30fd13399a79. Apologies for the back and forth on this, I am having trouble recreating the issue.

**Comment by marySalvi** [comment]
> The "Collecting Directory Data" message doesn't go away; I was selecting an empty directory for output.
> 
> It also didn't go away in a directory that had no sub-directories but had images.

fixed in b283bb6be24d465e19636051ad40985b2db5e949

**Review by manthey — APPROVED** [review]

**Pull request merged**
